apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pg-notify-mq
  labels:
    name: pg-notify-mq
spec:
  replicas: 1  # only can be one atm not a scaled service
  template:
    metadata:
      labels:
        name: pg-notify-mq 
    spec:
      containers:
      - name: listener
        image: 7imbrook/pg-rabbit-notify
        volumeMounts:
          - mountPath: "/opt/"
            name: config
            readOnly: true
      volumes:
        - name: config
          secret:
            secretName: pg-notify-config
