version: '3.7'
services: 
  nginx:
    build: ./conf
    ports:
      - "80:8081"
  webpack-dev:
    image: node:11.3.0
    command: npm run container
    working_dir: /root/project
    volumes: 
      - "./:/root/project"
    ports:
      - "8080:8080"
    extra_hosts: 
      - "postgrest-api:10.245.43.43"
