version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Verifiy
          command: kubectl version && helm version
      - run:
          name: Build/Deploy
          command: ./deploy_service.sh 
