version: '3.1'

services:
  updater:
    image: '7imbrook/auto-service-updater'
    ports:
      - 30000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      - CONFIG_PATH=/run/secrets/config
    secrets:
      - source: updater_config
        target: config

secrets:
  updater_config:
    file: ./updater_config.txt
