version: '3'
services:
  # gateway:
  #   image: '7imbrook/life'
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   depends_on:
  #     - api
  #     - auth
  #   volumes: 
  #     - caddycache:/root/.caddy
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.labels.edge == true

  # build my own image for this, this is ugly
  api:
    image: '7imbrook/postgrest'
    deploy:
      replicas: 1
    environment:
      - JWT_SECRET_FILE=/run/secrets/jwtkey
      - POSTGRES_DB=postgres
      - POSTGRES_ROLE=readonly
      - POSTGRES_PASS_FILE=/run/secrets/aws_rds_life_password
      - POSTGRES_HOST_FILE=/run/secrets/rds_host

  # auth:
  #   deploy:
  #     replicas: 1
  #   environment:
  #     - JWT_SECRET_FILE=/run/secrets/jwtkey
  #     - POSTGRES_PASSWORD_FILE=/run/secrets/aws_rds_life_password
  #   image: '7imbrook/auth:latest'

# volumes:
#   caddycache:
