replicaCount: 1

image:
    repository: 7imbrook/auth

healthEndpoint: "/health"

container:
    port: 5000 

ingress:
    enabled: false 

environment:
    - name: REDIS_PASSWORD 
      valueFrom:
        secretKeyRef:
            name: redis
            key: redis-password 

secrets:
    - jwt-keys