version: '3.7'
services: 
  nginx:
    build: .
    ports:
      - 8000:80
  auth-service:
    # We need a 200 response for auth. Actually deploy differs
    image: python:2.7
    command: python -m SimpleHTTPServer 500