---
# Source: templates/config.yml
version: 2.1
jobs:
  save_deploy_configs:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: /personal-page
    steps:
      - checkout
      - persist_to_workspace:
          root: deploy
          paths:
            - .
  auth_app:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: /personal-page
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Authenticate
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build
          command: docker build -t local_build_only_auth ./auth
      - run:
          name: Tag and Push
          command: |
            docker tag local_build_only_auth_app 7imbrook/auth;
            docker push 7imbrook/auth | tee $CIRCLE_WORKING_DIRECTORY/push_log_auth_app.log
      - run:
          name: Save Build Metadata
          command: |
            BUILD_SHA=$(tail -n 1 $CIRCLE_WORKING_DIRECTORY/push_log_auth_app.log | cut -d':' -f 4 | cut -d' ' -f 1)
            mkdir -p $CIRCLE_WORKING_DIRECTORY/outputs/meta;
            echo $BUILD_SHA > $CIRCLE_WORKING_DIRECTORY/outputs/meta/BUILD_SHA_AUTH_APP
      - persist_to_workspace:
          root: outputs
          paths:
            - meta
  mailer_app:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: /personal-page
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Authenticate
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build
          command: docker build -t local_build_only_auth ./auto-mailer
      - run:
          name: Tag and Push
          command: |
            docker tag local_build_only_mailer_app 7imbrook/mailer;
            docker push 7imbrook/mailer | tee $CIRCLE_WORKING_DIRECTORY/push_log_mailer_app.log
      - run:
          name: Save Build Metadata
          command: |
            BUILD_SHA=$(tail -n 1 $CIRCLE_WORKING_DIRECTORY/push_log_mailer_app.log | cut -d':' -f 4 | cut -d' ' -f 1)
            mkdir -p $CIRCLE_WORKING_DIRECTORY/outputs/meta;
            echo $BUILD_SHA > $CIRCLE_WORKING_DIRECTORY/outputs/meta/BUILD_SHA_MAILER_APP
      - persist_to_workspace:
          root: outputs
          paths:
            - meta
  main:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: /personal-page
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Authenticate
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build
          command: docker build -t local_build_only_auth .
      - run:
          name: Tag and Push
          command: |
            docker tag local_build_only_main 7imbrook/life;
            docker push 7imbrook/life | tee $CIRCLE_WORKING_DIRECTORY/push_log_main.log
      - run:
          name: Save Build Metadata
          command: |
            BUILD_SHA=$(tail -n 1 $CIRCLE_WORKING_DIRECTORY/push_log_main.log | cut -d':' -f 4 | cut -d' ' -f 1)
            mkdir -p $CIRCLE_WORKING_DIRECTORY/outputs/meta;
            echo $BUILD_SHA > $CIRCLE_WORKING_DIRECTORY/outputs/meta/BUILD_SHA_MAIN
      - persist_to_workspace:
          root: outputs
          paths:
            - meta
  deploy:
    docker:
      - image: 7imbrook/ci-deploy-tools
    working_directory: /root/deploy
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate Cluster
          command: ./run_helm_release.sh auth
      - run:
          name: Deploy Helm Release
          command: ./run_helm_release.sh deploy

workflows:
  version: 2
  deployment:
    jobs:
      - save_deploy_configs
      - auth_app
      - mailer_app
      - main
      - deploy:
          requires:
            - save_deploy_configs
            - auth_app
            - mailer_app
            - main
          filters:
            branches:
              only:
                - master
                - staging
