replicaCount: 1

image:
    repository: 7imbrook/door

healthEndpoint: "/health"

container:
    port: 5000 

ingress:
    enabled: true
    hosts:
        - door.timbrook.dev
    paths:
        - /

environment:
    - name: PARTICLE_DEVICE
      valueFrom:
        secretKeyRef:
            name: particle-token
            key: token
    - name: PARTICLE_TOKEN
      valueFrom:
        secretKeyRef:
            name: particle-token
            key: token
    - name: TWILIO_AUTH
      valueFrom:
        secretKeyRef:
            name: twilio-token
            key: key